"""Initial migration.

Revision ID: 036f07a13b23
Revises: 
Create Date: 2022-01-05 22:27:55.983945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '036f07a13b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'receipt_detail', 'receipt', ['id'], ['id'])
    op.alter_column('room', 'rental_voucher',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('room', 'image',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=150),
               nullable=False)
    op.alter_column('room', 'descriptions',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20000),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=True)
    op.alter_column('room', 'descriptions',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20000),
               nullable=True)
    op.alter_column('room', 'image',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=150),
               nullable=True)
    op.alter_column('room', 'rental_voucher',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'receipt_detail', type_='foreignkey')
    op.drop_column('receipt', 'user_id')
    # ### end Alembic commands ###
