"""Initial migration.

Revision ID: 297696f805c7
Revises: 8e82975bda04
Create Date: 2022-01-08 11:02:11.752480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297696f805c7'
down_revision = '8e82975bda04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('receive_day', sa.String(length=50), nullable=True),
    sa.Column('pay_day', sa.String(length=50), nullable=True),
    sa.Column('person_amount', sa.Integer(), nullable=True),
    sa.Column('rental_voucher_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rental_voucher_detail_id'], ['rental_voucher_detail.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_room')
    # ### end Alembic commands ###
