"""Initial migration.

Revision ID: 5d183fecee28
Revises: 297696f805c7
Create Date: 2022-01-08 11:15:52.098235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d183fecee28'
down_revision = '297696f805c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_room', sa.Column('image', sa.String(length=150), nullable=False))
    op.drop_column('booking_room', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_room', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('booking_room', 'image')
    # ### end Alembic commands ###
