"""Initial migration.

Revision ID: b6db8fa48e7f
Revises: 
Create Date: 2022-01-06 21:03:14.699362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6db8fa48e7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_detail', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipt_detail', 'receipt', ['receipt_id'], ['id'])
    op.add_column('rental_voucher', sa.Column('booking_date', sa.DateTime(), nullable=True))
    op.drop_column('rental_voucher', 'start_date')
    op.add_column('rental_voucher_detail', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('rental_voucher_detail', sa.Column('visit_name_id', sa.Integer(), nullable=False))
    op.add_column('rental_voucher_detail', sa.Column('nation', sa.String(length=100), nullable=True))
    op.alter_column('rental_voucher_detail', 'visit_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=50),
               nullable=False)
    op.drop_column('rental_voucher_detail', 'address')
    op.drop_column('rental_voucher_detail', 'cart_id')
    op.alter_column('room', 'rental_voucher',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('room', 'image',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=150),
               nullable=False)
    op.alter_column('room', 'descriptions',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20000),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=True)
    op.alter_column('room', 'descriptions',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20000),
               nullable=True)
    op.alter_column('room', 'image',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=150),
               nullable=True)
    op.alter_column('room', 'rental_voucher',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('rental_voucher_detail', sa.Column('cart_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rental_voucher_detail', sa.Column('address', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100), nullable=True))
    op.alter_column('rental_voucher_detail', 'visit_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=50),
               nullable=True)
    op.drop_column('rental_voucher_detail', 'nation')
    op.drop_column('rental_voucher_detail', 'visit_name_id')
    op.drop_column('rental_voucher_detail', 'email')
    op.add_column('rental_voucher', sa.Column('start_date', mysql.DATETIME(), nullable=True))
    op.drop_column('rental_voucher', 'booking_date')
    op.drop_constraint(None, 'receipt_detail', type_='foreignkey')
    op.drop_column('receipt_detail', 'receipt_id')
    # ### end Alembic commands ###
