"""Initial migration.

Revision ID: e85c7a4834bd
Revises: 
Create Date: 2022-01-04 19:23:00.140728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e85c7a4834bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_voucher_detail', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('rental_voucher_detail', sa.Column('visit_name_id', sa.Integer(), nullable=False))
    op.add_column('rental_voucher_detail', sa.Column('nation', sa.String(length=100), nullable=True))
    op.alter_column('rental_voucher_detail', 'visit_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=False)
    op.drop_column('rental_voucher_detail', 'address')
    op.drop_column('rental_voucher_detail', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_voucher_detail', sa.Column('cart_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rental_voucher_detail', sa.Column('address', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True))
    op.alter_column('rental_voucher_detail', 'visit_name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               nullable=True)
    op.drop_column('rental_voucher_detail', 'nation')
    op.drop_column('rental_voucher_detail', 'visit_name_id')
    op.drop_column('rental_voucher_detail', 'email')
    # ### end Alembic commands ###
